security:

    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    #acl:
    #    connection: default

    role_hierarchy:
        ROLE_APP_API:     [ROLE_API]
        ROLE_ADMIN:       [ROLE_USER, ROLE_SONATA_ADMIN, ROLE_APP_API]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
        SONATA:
            - ROLE_SONATA_PAGE_ADMIN_PAGE_EDIT  # if you are using acl then this line must be commented

    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # -> custom firewall for the admin area of the URL
        admin:
            pattern:            '^/admin/(.*)'
            context:            user
            form_login:
                provider:       fos_userbundle
                login_path:     sonata_user_admin_security_login
                use_forward:    false
                check_path:     sonata_user_admin_security_check
                failure_path:   null
            logout:
                path:           sonata_user_admin_security_logout
                target:         sonata_user_admin_security_login
            anonymous:          true
        # -> end custom configuration

        # -> custom firewall for the OAuth
        oauth_token:
            pattern:    '^/oauth/v2/token'
            security:   false

        oauth_authorize:
            pattern:    '^/oauth/v2/auth'
            # Add your favorite authentication process here
            form_login:
                login_path: fos_user_security_login
                check_path: fos_user_security_check
                provider:   fos_userbundle
            anonymous: true
        # -> end custom configuration

        # -> custom firewall for the Api
        api:
            pattern:    '^/api/v1(.*)'
            fos_oauth:  true
            stateless:  true
            anonymous:  false # can be omitted as its default value
        # -> end custom configuration

        # default login area for standard users
        # This firewall is used to handle the public login area
        # This part is handled by the FOS User Bundle
        main:
            pattern:             /.*
            context:             user
            form_login:
                provider:       fos_userbundle
                login_path:     fos_user_security_login
                use_forward:    false
                check_path:     fos_user_security_check
                failure_path:   null
            logout:             true
            #logout:
            #    invalidate_session: true
            #    handlers:
            #        - fos_http_cache.user_context.logout_handler
            anonymous:          true

            # activate different ways to authenticate

            # http_basic: true
            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: true
            # https://symfony.com/doc/current/security/form_login_setup.html

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
    # Admin login page needs to be accessed without credential
    - { path: ^/[^/]+/admin/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/[^/]+/admin/logout$, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/[^/]+/admin/login_check$, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/[^/]+/admin/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/[^/]+/admin/, role: [ROLE_ADMIN, ROLE_SONATA_ADMIN] }

    # OAuth / API
    - { path: '^/[^/]+/',  roles: [ IS_AUTHENTICATED_FULLY ] }
    - { path: ^/[^/]+/api/doc,  roles: IS_AUTHENTICATED_ANONYMOUSLY }
